on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'

name: Release executables for Windows and macOS

jobs:
  build-windows:
    name: Upload Release Asset Windows
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [3.6]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
      - name: Set up code
        run: |
          git submodule update --init --recursive
          python bootstrap.py
      - name: Run pyinstaller
        run: |
          python bootstrap.py --mode install
      - name: Apply code sign
        run: |
          git clone https://github.com/LUXROBO/code-sign
          cd code-sign
          ./SignTool.exe sign /v /f ./20210430-328240_luxrobo_com_chain.pfx /p ${{ secrets.WIN_CODESIGN_PASSWORD }} /tr http://timestamp.digicert.com /td sha384 /fd sha384 ../dist/modi_updater.exe
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/modi_updater.exe
          asset_name: modi_updater.exe
          tag: ${{ github.ref }}
          overwrite: true
  build-macos:
    name: Upload Release Asset macOS
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: [3.6]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
      - name: Set up code
        run: |
          git submodule update --init --recursive
          python bootstrap.py
      - name: Run pyinstaller
        run: |
          python bootstrap.py --mode install
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/modi_updater
          asset_name: modi_updater
          tag: ${{ github.ref }}
          overwrite: true

